version: '3'
services: 
    mssql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        environment: 
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
        ports: 
            - "1433:1433"
    shopapp:
        build: .
        ports: 
            - "8080:80"
            